title: "技术博客"
description: "分享技术学习笔记"
url: "https://ufogxl.github.io"

remote_theme: cotes2020/jekyll-theme-chirpy

markdown: kramdown
permalink: /:categories/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      toc: true
      mermaid: true
      math: true